---
title: "First R Markdown"
author: "Gian Nicole Villamayor, Jessica Dela Cruz, John Lester Santos, Rollic Conducto"
date: "12/07/2021"
output: 
  html_document:
    code_download: true

---

***

### I. Aside from the reasons mentioned in class, why do we need to study and analyze data?
\

#### 1. It can determine Strengths and Weaknesses.

+ There can be many interpretations that can be extracted in a given data. It is important to learn and analyze data because it is our job as human beings *to extract meaning from the raw data.* These data can show patterns that may happen in the future based on the behavior of the data in the present. Data analyzation is important for companies or organizations because they can determine what parts are they **the strongest or the weakest.**

#### 2. Predict an outcome

+ In every action that we do, there are data being generated. It is important to analyze these data as it gives meaning to the things that we do and how things around us work. When statistics is applied to data it can predict what outcome is **most likely to happen**. This is why it can help in planning and decision making in business, research and in many other fields. For example, if I were to run a business in a certain area, analyzing relevant data can help determine what it should be for my business to be most likely to succeed and profit in a long term. 


***

### II. Cite atleast one instance or application where data science was used and contributed on policy-making, day-to-day decisions, knowing market trends, and scientific researches.
\

#### 1.Search Engines.

+ Data science is used in **search engines** wherein it makes use of algorithms that sorts the websites that is applicable to the term that was searched. Numerous websites can appear in searching for an object. Data science makes sure that the sites that are on top are the ones that people click the most or the information is the most reliable.

#### 2. Recommendation Systems

+ One application of Data Science is in **recommendation systems** of applications such as Netflix, Spotify, Lazada, etc. The data from the previous choices of the user are collected and algorithms are used to determine what other items, songs or movies a user might prefer so that the system could recommend it to the user. By having this system, both the user and the provider benefit as it shortens the time of finding items and the user is most likely to be satisfied with the application.


***

### III. Propose atleast one data science topic that you want to pursue: Have a broad description of the topic, describe the availability of the data, what kinds of statistical method you think you will need, and who would benefit this study.
\

#### 1. Behavioral Score Feature in Dota 2

+ Dota 2 is a MOBA game that is known by many people. One of the features in the is that it calculates your **behavioral score** per game in terms of the reports you have received or the games you have abandoned. You can be reported due to **communication abuse, intentional feeding, mechanical ability abuse.** With the data of the behavioral score, we can make it more significant if we were to use this data. An idea is that the behavioral score can be paired with the KDA status of the player to determine if he/she has **anger issues, is a "smurf", or needs to be coached.** The MCT of the KDA shall be needed in order to describe the correlation of the behavioral scores and the KDA of the players. The players of Dota shall benefit the topic because coaching can improve the play style of a player, smurfs must be banned, and other treatment shall be given to players with anger issues. 

#### 2. Filipino's Preference on Movies and Series  

+ Filipinos are one of the top subscribers in streaming services and Netflix is the most popular one in the Philippines. In the app, we are able to see the daily trend for shows and movies. This data can be categorized by the **genre** and the **region** where it was produced and from this the preference of the Filipinos on movies and shows can be described and analyzed using *descriptive statistics*. The results can be beneficial to the filmmakers to be able to identify what they should give to the Filipino viewers. On the other hand, the Filipinos will also benefit from having more choices of their own preference. Further researches can also be done to investigate the reasons for the preference.

***
		
***

# References

```{css, echo = FALSE}

  h1 {
  color: gray();
  }
  body {
    text-align: justify;
  }
  ```
  What Is a Recommendation Engine and How Does It Work? (2020, September 10). Appier. <https://www.appier.com/blog/what-is-a-recommendation-engine-and-how-does-it-work/?fbclid=IwAR3qj5B65PCh5wyWeTZGS86eyst1tM-moAmHuxA_pFsefJKo1hIBe-bfosk>

